# automatically generated by the FlatBuffers compiler, do not modify

# namespace: SmartCamera

import flatbuffers
from flatbuffers.compat import import_numpy

np = import_numpy()


class WatchTimePair(object):
    __slots__ = ["_tab"]

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = WatchTimePair()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsWatchTimePair(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)

    # WatchTimePair
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # WatchTimePair
    def Start(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(
                flatbuffers.number_types.Uint64Flags, o + self._tab.Pos
            )
        return 0

    # WatchTimePair
    def End(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(
                flatbuffers.number_types.Uint64Flags, o + self._tab.Pos
            )
        return 0


def WatchTimePairStart(builder):
    builder.StartObject(2)


def Start(builder):
    return WatchTimePairStart(builder)


def WatchTimePairAddStart(builder, start):
    builder.PrependUint64Slot(0, start, 0)


def AddStart(builder, start):
    return WatchTimePairAddStart(builder, start)


def WatchTimePairAddEnd(builder, end):
    builder.PrependUint64Slot(1, end, 0)


def AddEnd(builder, end):
    return WatchTimePairAddEnd(builder, end)


def WatchTimePairEnd(builder):
    return builder.EndObject()


def End(builder):
    return WatchTimePairEnd(builder)
