console_access_settings:
  console_endpoint: "https://console.aitrios.sony-semicon.com/api/v1"
  portal_authorization_endpoint: "https://auth.aitrios.sony-semicon.com/oauth2/default/v1/token"
  client_secret: "26whfzjOjDbM-0vbtDu3UAUDtvjHt-gcVh2e146jpzMHU8buUukS2YXokN-6H-vV"
  client_id: "0oadamycfzZr7VWd2697"
