data_source_settings:
  mode: "console"     # "console" or "local"
  console_data_settings:
    setting_path: "./config/console_access_settings.yaml"
    device_id: "sid-100A50500A2001027864012000000000"
    sub_directory_name: "20231003011600967"

crowd_count_settings:
  param_file: "./config/local_default_param.yaml"
